### ISSUE TITLE
wrong linkedin link

### ISSUE THREAD

**Issue by mohsenSy** [somarkn99/Harry-Potter-ReactJS-Api#1]
At the end of your README there are two links for your website and your linkedin account, actually both of them point to your website.

Fix your linkedin account link with the right one

**Comment by somarkn99** [comment]
> At the end of your README there are two links for your website and your linkedin account, actually both of them point to your website.
> 
> Fix your linkedin account link with the right one

Thanks for the observation. This happened because of the speed at work.
I adjusted it immediately.
Thank you.
