### ISSUE TITLE
List items must have a unique key

### ISSUE THREAD

**Issue by mohsenSy** [somarkn99/Harry-Potter-ReactJS-Api#2]
When using lists in react you must provide a unique key for each list item so react can render the right items even if after they are deleted from state, you have this error in the console log

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `CharacterGrid`. See https://reactjs.org/link/warning-keys for more information.
    at CharacterItems (http://localhost:3000/static/js/bundle.js:494:5)
    at CharacterGrid (http://localhost:3000/static/js/bundle.js:409:5)
    at div
    at App (http://localhost:3000/static/js/bundle.js:40:76)
```

Which means you don't have a unique key for items in the characters list, if you look at your code [here](https://github.com/somarkn99/Harry-Potter-ReactJS-Api/blob/master/src/components/charchters/CharacterGrid.js#L10) you are using `item.char_id` as key but `char_id` is not defined in the item object, you need to either find an attribute that is suitable as key in the items object or add a new unique attribute to it

**Comment by somarkn99** [comment]
Thank you for providing this issue. Its ready now
